name: Run Puppeteer Cron

on:
  schedule:
    - cron: "0 * * * *"  # Запуск щогодини
  workflow_dispatch:  # Дозволяє запускати вручну

jobs:
  run-cron:
    runs-on: ubuntu-22.04  # Швидше, ніж `ubuntu-latest`

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v4

      - name: Встановлення Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Кешування Puppeteer
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}
          restore-keys: puppeteer-

      - name: Встановлення залежностей
        run: npm install

      - name: Запуск скрипту Puppeteer
        run: node cron.js
