name: Run Puppeteer Cron

on:
  schedule:
    # з 00:00 до 08:00 — щогодини
    - cron: "0 0-8 * * *"

    # з 09:00 до 19:30 — кожні 30 хвилин
    - cron: "0,30 9-19 * * *"

    # з 20:00 до 23:00 — щогодини
    - cron: "0 20-23 * * *"
  workflow_dispatch:  # Дозволяє запускати вручну

jobs:
  run-cron:
    runs-on: ubuntu-22.04  # Швидше, ніж `ubuntu-latest`

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v4

      - name: Встановлення Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Кешування Puppeteer
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}
          restore-keys: puppeteer-

      - name: Встановлення залежностей
        run: npm install

      - name: Запуск скрипту Puppeteer
        run: node cron.js
        env:
          CRON_PASSWORD: ${{ secrets.CRON_PASSWORD }}
